viyaapp:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - VIYA_SERVER=
      - CLIENTID=uidemos
      - CLIENTSECRET=secret
      - APPHOST=localhost
      - APPNAME=uidemos
      - APPPORT=8080

