viyaapp:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - VIYA_SERVER=http://kdk2013.fbi.sashq-d.openstack.sas.com
      - DEBUG=auth,getapp,bell,loc,cookie,cookies
      

