version: "3.3"
services:
  myapi:
      build: .
      restart: always
      ports:
        - 8080:8080
      environment:
        - VIYA_SERVER=
        - CLIENTID=viyaapi
        - CLIENTSECRET=secret
        - APPNAME=viyaapi
# Mounts volume for tokens(if using saved tokens, and other files)
# volumes:
#    - c:/Public/dev/data/sas:/sasin



