apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


secretGenerator:
  - name: tls-secret
    type: kubernetes.io/tls
    files:
    - ./secrets/tls.crt
    - ./secrets/tls.key
# - name: clientid-secret
#     type: Opaque
#     files:
#     - ./secrets/CLIENTSECRET
    
resources:
- service.yaml
- deployment.yaml
- ingress.yaml


