apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
# Secret generator
# Maps to TLS_KEY and TLS_CERT in docker-compose|(.env + Dockerfile in bareos)
secretGenerator:
  - name: tls-secret
    type: kubernetes.io/tls
    files:
    - ./secrets/tls.crt
    - ./secrets/tls.key
  - name: clientid-secret
    type: Opaque
    files:
    - ./secrets/CLIENTSECRET
# env variables
# maps to env of docker-compose/(.env + Dockefile in bareos)



